### ISSUE TITLE
Implement plugin.sendMoney

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-plugin-xrp-asym-server#11]
It seems that https://github.com/interledgerjs/ilp-plugin-xrp-asym-server/blob/master/index.js#L498 is used instead of https://github.com/interledgerjs/ilp-plugin-xrp-asym-server/blob/master/index.js#L520-L524?

Obviously, since this plugin exposes only one LPI, but in reality represents possibly many connected peers, it's not possible to know *who* to send money to when `plugin.sendMoney` is called. The same problem exists for `plugin.sendData`, which this plugin inherits from ilp-plugin-mini-accounts, but there it's solved with [deep packet inspection](https://github.com/interledgerjs/ilp-plugin-mini-accounts/blob/master/index.js#L170). That same trick cannot be used here.

Maybe we should just stop pursuing the concept of exposing only one LPI? Otherwise, maybe we should change the LPI to support server plugins?

**Comment by sharafian** [comment]
Given the current LPI, where a server plugin is behaving as a connector, this plugin is performing the correct behavior. Can we close this and continue discussion of the issue of whether the LPI should change in RFCs?
