### ISSUE TITLE
deal with undefined outgoing balance

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-plugin-xrp-asym-server#14]
```sh
sending money to account 1000 test.amundsen.bmp.btp18q1.6wRdeNJzEHNIsDAMAdKbdVLWIqu8b6-Bs-xVNZqplQw.XmWKc9DrpBs.J8ZZyfb8T3b6U6RrF-HCrQyg 2803620212
getting outgoing balnce from store 6wRdeNJzEHNIsDAMAdKbdVLWIqu8b6-Bs-xVNZqplQw:outgoing_balance undefined
2018-02-08T16:56:12.141Z ilp-plugin-xrp-server debug failed to pay account.
            destination=test.amundsen.bmp.btp18q1.6wRdeNJzEHNIsDAMAdKbdVLWIqu8b6-Bs-xVNZqplQw.XmWKc9DrpBs.J8ZZyfb8T3b6U6RrF-HCrQyg
            error=BigNumber Error: new BigNumber() not a number: undefined
    at raise (/home/michiel/amundsen/node_modules/ilp-plugin-xrp-asym-server/node_modules/bignumber.js/bignumber.js:1191:25)
    at /home/michiel/amundsen/node_modules/ilp-plugin-xrp-asym-server/node_modules/bignumber.js/bignumber.js:1179:33
    at new BigNumber (/home/michiel/amundsen/node_modules/ilp-plugin-xrp-asym-server/node_modules/bignumber.js/bignumber.js:194:67)
    at Account.getOutgoingBalance (/home/michiel/amundsen/node_modules/ilp-plugin-xrp-asym-server/src/account.js:117:12)
    at Plugin._sendMoneyToAccount (/home/michiel/amundsen/node_modules/ilp-plugin-xrp-asym-server/index.js:531:36)
    at util._requestId.then (/home/michiel/amundsen/node_modules/ilp-plugin-xrp-asym-server/index.js:509:34)
    at <anonymous>

**Comment by michielbdejong** [comment]
also: getting client channel 6wRdeNJzEHNIsDAMAdKbdVLWIqu8b6-Bs-xVNZqplQw:client_channel undefined

**Comment by michielbdejong** [comment]
@sharafian i tried to make the outgoing balance default to '0', but then it fails on getting the client channel id from the store. Is ilp-connector's default store in-memory only? if so, and amundsen regularly reboots, then i can probably work around this by configuring an on-disk store?

still, it would be good if this plugin would deal more gracefully with store flushes.

**Comment by sharafian** [comment]
If the store flushed, the server plugin wouldn't know that it previously had a client channel so I'm not sure how that could cause an error like this. I believe the connector defaults to using leveldown as its store, though, which is persistent.

**Comment by sharafian** [comment]
this behavior makes it look like the client channel failed to be created, which is what we've been seeing often while using `moneyd` on the testnet

**Comment by michielbdejong** [comment]
When I connect my moneyd with fresh credentials I see setClientChannel storing `DJC2pW-t8Bwoe1_Ru9RZ9viFqlIbv6T27kE1Skh1gb8:client_channel` `17552A1F1398AD5F2390A502E810640B8C67AD4B5BEB61F5F32A52E9DF60FC9E`.

Then when I `ilp-curl https://letter-shop-testnet.herokuapp.com` from my laptop, in the Amundsen log I see it tries to get client channel `6wRdeNJzEHNIsDAMAdKbdVLWIqu8b6-Bs-xVNZqplQw:client_channel` but receives `undefined` from the store. That makes me think `6wRdeNJzEHNIsDAMAdKbdVLWIqu8b6-Bs-xVNZqplQw:client_channel` is supposed to be the channel from amundsen to the letter shop

**Comment by michielbdejong** [comment]
ah, i know what's going on - the letter shop connects using ilp-plugin-btp, so it never sends a claim.  continued in https://github.com/michielbdejong/letter-shop/issues/4 :)
