### ISSUE TITLE
Allow only one paychan per XRP address

### ISSUE THREAD

**Issue by dappelt** [interledgerjs/ilp-plugin-xrp-asym-server#7]
The default bandwidth (even for a new paychan/account) is 2000 drops. An attacker can easily steal from the connector by opening many paychans to the connector, which cost 10 drops a piece, make the connector forward 2000 drops on each paychan and never send a claim.

One mitigation to this problem would be if the connector allows only one paychan per XRP address. An attacker could steal 1990 drops, but not more.

**Comment by emschwartz** [comment]
:+1: because even having an account costs 20 XRP so it wouldn't be worth it to open more accounts just to steal from a connector

**Comment by sharafian** [comment]
Another option is for us to set the bandwidth to 0 for all clients. This would mean that they always need to pre-fund, and it would be impossible for any bandwidth-stealing attacks going forward. Pre-funding is already supported via the connector's `balance` configuration, so this would largely be a configuration change

**Comment by justmoon** [comment]
I think we said we wanted to be able to have multiple channels per account so that you can have multiple clients connected at the same time. (Two clients can't use the same channel at the same time.)

So we have to go with the balance configuration solution I think.

**Comment by michielbdejong** [comment]
Why can't we just allow 2000 drops of unsecuredAmount per XRP account instead of per payment channel, and then still allow people to open as many channels as they want, but only get to use up their starter balance once?

**Comment by peterjkrey** [comment]
I second @michielbdejong .  Total unsecuredAmount can be netted across all channels to a select XRP address.

**Comment by dappelt** [comment]
Looks like @justmoon and @sharafian went with the [prefunding](https://github.com/interledgerjs/ilp-connector/pull/412) option.

Can this be closed?

**Comment by michielbdejong** [comment]
I guess the question is if it's enough if ilp-connector only supports prefunding, or if we want to allow other people to configure a non-zero limit on the per-address unsecuredAmount
